# SPDX-License-Identifier: GPL-2.0-only
dtb-$(CONFIG_ARCH_STM32) += \
	stm32mp257f-dk.dtb \
	stm32mp257f-ev1.dtb \
        myb-stm32mp257x-1GB.dtb \
        myb-stm32mp257x-2GB.dtb \
        myb-stm32mp257x-1GB-ethswitch.dtb \
        myb-stm32mp257x-2GB-ethswitch.dtb
